app:
  name: Objective Detection and Tracker
  version: 1.0.0
  env: development

data:
  input: inputs/videos
  output: outputs/videos
  model: models

detector:
  type: yolo26n
  conf_threshold: 0.5
  iou_threshold: 0.4
  classes : [2] # null for all class,
  max_det: 100
  device: 0 # 0 for GPU, -1 for CPU

counter:
  # - type: line
  #   points: [[100, 200], [500, 200]]
  #   color: [0, 0, 255] # BGR format
  #   thickness: 2

  # - type: zone
  #   points: [[200, 50], [500, 200]]
  #   color: [0, 0, 255] # BGR format
  #   thickness: 2

  # - type: lane_zone
  #   points: [[203, 83], [382, 83], [482, 200], [133, 200]]
  #   color: [0, 0, 255] # BGR format
  #   thickness: 2

  - type: multiple_lane_zone
    points: [[[220, 55], [86, 285], [192, 285], [256, 55]],
             [[192, 285], [256, 55], [294, 55], [315, 285]],
             [[294, 55], [315, 285], [437, 285], [332, 55]],
             [[437, 285], [332, 55], [363, 55], [541, 285]]]
    colors: [[0, 0, 255], [0, 255, 0], [255, 0, 0], [255, 255, 0]] # BGR format
    thickness: 2


saver:
  save_images: false
  save_videos: false
  save_detections: false
  save_crops: false

tracker:
  type: bytetrack # or strongsort
  max_age: 30
  n_init: 3
  iou_threshold: 0.3

visualizer:
  show_detections: true
  show_tracks: true
  show_count: true
  # show_fps: true
  # show_time: true

speed:
  enable: true
  FPS: 30 
  # tính thời gian lấy mẫu distance
  pixel_per_meter: 5
  # calib bằng pixel_per_meter = pixel / meter : phải biết được kích thước thực tế của 1 vật tron video để calib ra pixel_per_meter
  buffer_size: 5 
  max_speed: [70, 70, 70, 70] # km/h, tốc độ tối đa cho từng làn