app:
  name: Objective Detection and Tracker
  version: 1.0.0
  env: development

data:
  input: inputs/videos
  output: outputs/videos
  model: models

detector:
  type: yolov8n-visdrone
  conf_threshold: 0.5
  iou_threshold: 0.4
  classes : [2] # null for all class,
  max_det: 100
  device: 0 # 0 for GPU, -1 for CPU

counter:
  - type: line
    points: [[75, 540], [1332, 540]]
    color: [0, 0, 255] # BGR format
    thickness: 2

  # - type: zone
  #   points: [[200, 50], [500, 200]]
  #   color: [0, 0, 255] # BGR format
  #   thickness: 2

  # - type: lane_zone
  #   points: [[203, 83], [382, 83], [482, 200], [133, 200]]
  #   color: [0, 0, 255] # BGR format
  #   thickness: 2

  # - type: multiple_lane_zone
  #   points: [[[220, 55], [86, 285], [192, 285], [256, 55]],
  #            [[192, 285], [256, 55], [294, 55], [315, 285]],
  #            [[294, 55], [315, 285], [437, 285], [332, 55]],
  #            [[437, 285], [332, 55], [363, 55], [541, 285]]]
  #   colors: [[0, 0, 255], [0, 255, 0], [255, 0, 0], [255, 255, 0]] # BGR format
  #   thickness: 2

  # - type: multiple_lane_zone
  #   points: [[[770, 1075], [770, 830], [860, 830], [860, 1075]],
  #            [[860, 830], [860, 1075], [963, 1075], [963, 830]],
  #            [[1027, 1075], [1027, 830], [1115, 830], [1115, 1075]],
  #            [[1115, 830], [1115, 1075], [1218, 1075], [1218, 830]],
             
  #            [[770, 230], [770, 1], [860, 1], [860, 230]],
  #            [[860, 1], [860, 230], [970, 230], [970, 1]],
  #            [[1025, 230], [1025, 1], [1125, 1], [1125, 230]],
  #            [[1125, 1], [1125, 230], [1225, 230], [1225, 1]],

  #            [[1920, 420], [1370, 420], [1370, 570], [1920, 570]],
  #            [[1370, 570], [1920, 570], [1920, 725], [1370, 725]],

  #            [[620, 425], [5, 425], [5, 570], [620, 570]],
  #            [[5, 570], [620, 570], [620, 735], [5, 735]],
  #            ]
  #   colors: [[0, 0, 255], [0, 255, 0], [255, 0, 0], [255, 255, 0]] # BGR format
  #   thickness: 2




saver:
  save_images: false
  save_videos: false
  save_detections: false
  save_crops: false

tracker:
  type: bytetrack # or strongsort
  max_age: 30
  n_init: 3
  iou_threshold: 0.3

visualizer:
  show_detections: true
  show_tracks: true
  show_count: true
  # show_fps: true
  # show_time: true

speed:
  enable: false
  FPS: 30 
  # tính thời gian lấy mẫu distance
  pixel_per_meter: 21.7
  # calib bằng pixel_per_meter = pixel / meter : phải biết được kích thước thực tế của 1 vật tron video để calib ra pixel_per_meter
  buffer_size: 5 
  max_speed: [70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70] # km/h, tốc độ tối đa cho từng làn